### PR TITLE
Update offchain::ipfs to latest substrate

### PR DESCRIPTION
**Pull request by andskur**
Hey!
We have updated offchain::ipfs to latest substrate. Will be great if you can take a look at it.

### CODE REVIEW

**Comment by driemworks** [comment]
I've been working on something similar, except I first synced my repo with the substrate master branch and then rebuilt the changes from rs-ips/substrate on top of it.  It could be useful to compare https://github.com/mystery-team/substrate/commit/cf74e7657d9db7055a08b52662d835d9ef8a6104

**Comment by andskur** [comment]
@driemworks oh, great and thanks! I will take a look at your repo

**Comment by alxs** [comment]
@koivunej @ljedrz @aphelionz think you could take a moment to review this in the next few days? It was done as part of a W3F grant and we would like the PR to be merged before the milestone is accepted. The alternative would be a fork of this fork and the 'official' `offchain::ipfs` moving, which we would like to avoid.

**Comment by koivunej** [comment]
Thanks for the ping I had not noticed this PR. I am currently AFK but will be back next week, as is the same with the other mentioned.

**Comment by koivunej** [comment]
It would appear that we haven't found the time to review all of this or consider how does it work with the huge amount of progress which has happened in substrate in the meantime.

Something I do notice is that now in the fork by @andskur the previously single commit patch is now a result of two merges. While maintaining forks, we've found it to be the easiest to have a patch set which is occasionally rebased on top of a new upstream snapshot. This doesn't work with pull request workflow at all but that as a suggestion going forwards with the patch. This would better allow reviewing during upstreaming attempts as the diff would only be the actual changes, not a year full of changes.

As I suspect we will not have time to properly review this at least within the grant process, delaying it even more, it might be best to move forwards with the suggested fork of fork for now at least. We could add a link from our repo README to this newer fork and archive the repo for the time being.

cc: @alxs

**Comment by alxs** [comment]
Ah, that's too bad! So I think if you're not planning to maintain the project in the foreseeable future it would make sense to archive it, though seeing as we already have at least two forks of the project (see above, and definitely a bunch of others) being worked on maybe you want to link to both.

And yeah I also think rebasing first would be a cleaner and more sustainable approach to keeping this up to date with upstream. I wasn't looking at this delivery but I'll link to it here so the topic can be picked up by whoever is https://github.com/w3f/Grant-Milestone-Delivery/pull/254.

**Comment by MikeMS-sys** [comment]
Also agree with @koivunej  and appreciate the decision.
Thank you guys so much! Actually, we were inspired with your work and decided to use offchain::ipfs at our data storage solution for Substrate developers along the way updating it to the latest Substrate version, and we will support our fork up to date.

**Comment by koivunej** [comment]
I created the #6 to change the README so please make sure I got the fork links right, and if there should be some other repo linked please suggest it with the correct link.

**Comment by alxs** [comment]
Looks good. Feel free to close this PR.

**Pull request closed without merging**
